---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-azure-tnnova-io-azure-tnnova-io-v1-player
  failurePolicy: Fail
  name: vplayer-v1.kb.io
  rules:
  - apiGroups:
    - azure.tnnova.io.azure.tnnova.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - players
  sideEffects: None
