# permissions for end users to edit highscores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dx-olympics-highscore-controller
    app.kubernetes.io/managed-by: kustomize
  name: highscore-editor-role
rules:
- apiGroups:
  - azure.tnnova.io.azure.tnnova.io
  resources:
  - highscores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.tnnova.io.azure.tnnova.io
  resources:
  - highscores/status
  verbs:
  - get
