# permissions for end users to view players.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dx-olympics-highscore-controller
    app.kubernetes.io/managed-by: kustomize
  name: player-viewer-role
rules:
- apiGroups:
  - azure.tnnova.io.azure.tnnova.io
  resources:
  - players
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - azure.tnnova.io.azure.tnnova.io
  resources:
  - players/status
  verbs:
  - get
